services:
  board:
    image: portfolio/board:latest
    command: ["runserver", "-c", "/app/configs/board.config.yaml"]
    networks:
      - portfolio-backend-network
    ports:
      - "8080:8080"
      - "10010:10010"
    volumes:
      - ../.config/board.config.yaml:/app/configs/board.config.yaml
    depends_on:
      portfolio-backend-db:
        condition: service_healthy
      portfolio-backend-redis-node-5:
        condition: service_healthy

  auth:
    image: portfolio/auth:latest
    command: ["runserver", "-c", "/app/configs/auth.config.yaml"]
    networks:
      - portfolio-backend-network
    ports:
      - "8081:8081"
      - "10011:10011"
    volumes:
      - ../.config/auth.config.yaml:/app/configs/auth.config.yaml
    depends_on:
      portfolio-backend-db:
        condition: service_healthy
      portfolio-backend-redis-node-5:
        condition: service_healthy

  portfolio-backend-db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ../data/postgres:/var/lib/postgresql/data
    networks:
      - portfolio-backend-network

  portfolio-backend-redis-node-0:
    image: docker.io/bitnami/redis-cluster:7.2
    networks:
      - portfolio-backend-network
    volumes:
      - ../data/redis-cluster_data-0:/bitnami/redis/data
    environment:
      - "ALLOW_EMPTY_PASSWORD=yes"
      - "REDIS_NODES=portfolio-backend-redis-node-0 portfolio-backend-redis-node-1 portfolio-backend-redis-node-2 portfolio-backend-redis-node-3 portfolio-backend-redis-node-4 portfolio-backend-redis-node-5"

  portfolio-backend-redis-node-1:
    image: docker.io/bitnami/redis-cluster:7.2
    networks:
      - portfolio-backend-network
    volumes:
      - ../data/redis-cluster_data-1:/bitnami/redis/data
    environment:
      - "ALLOW_EMPTY_PASSWORD=yes"
      - "REDIS_NODES=portfolio-backend-redis-node-0 portfolio-backend-redis-node-1 portfolio-backend-redis-node-2 portfolio-backend-redis-node-3 portfolio-backend-redis-node-4 portfolio-backend-redis-node-5"

  portfolio-backend-redis-node-2:
    image: docker.io/bitnami/redis-cluster:7.2
    networks:
      - portfolio-backend-network
    volumes:
      - ../data/redis-cluster_data-2:/bitnami/redis/data
    environment:
      - "ALLOW_EMPTY_PASSWORD=yes"
      - "REDIS_NODES=portfolio-backend-redis-node-0 portfolio-backend-redis-node-1 portfolio-backend-redis-node-2 portfolio-backend-redis-node-3 portfolio-backend-redis-node-4 portfolio-backend-redis-node-5"

  portfolio-backend-redis-node-3:
    image: docker.io/bitnami/redis-cluster:7.2
    networks:
      - portfolio-backend-network
    volumes:
      - ../data/redis-cluster_data-3:/bitnami/redis/data
    environment:
      - "ALLOW_EMPTY_PASSWORD=yes"
      - "REDIS_NODES=portfolio-backend-redis-node-0 portfolio-backend-redis-node-1 portfolio-backend-redis-node-2 portfolio-backend-redis-node-3 portfolio-backend-redis-node-4 portfolio-backend-redis-node-5"

  portfolio-backend-redis-node-4:
    image: docker.io/bitnami/redis-cluster:7.2
    networks:
      - portfolio-backend-network
    volumes:
      - ../data/redis-cluster_data-4:/bitnami/redis/data
    environment:
      - "ALLOW_EMPTY_PASSWORD=yes"
      - "REDIS_NODES=portfolio-backend-redis-node-0 portfolio-backend-redis-node-1 portfolio-backend-redis-node-2 portfolio-backend-redis-node-3 portfolio-backend-redis-node-4 portfolio-backend-redis-node-5"

  portfolio-backend-redis-node-5:
    image: docker.io/bitnami/redis-cluster:7.2
    networks:
      - portfolio-backend-network
    volumes:
      - ../data/redis-cluster_data-5:/bitnami/redis/data
    healthcheck:
      test:
        [
          "CMD",
          "redis-cli",
          "-h",
          "localhost",
          "-p",
          "6379",
          "-a",
          "bitnami",
          "ping",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      - portfolio-backend-redis-node-0
      - portfolio-backend-redis-node-1
      - portfolio-backend-redis-node-2
      - portfolio-backend-redis-node-3
      - portfolio-backend-redis-node-4
    environment:
      - "ALLOW_EMPTY_PASSWORD=yes"
      - "REDIS_CLUSTER_REPLICAS=1"
      - "REDIS_NODES=portfolio-backend-redis-node-0 portfolio-backend-redis-node-1 portfolio-backend-redis-node-2 portfolio-backend-redis-node-3 portfolio-backend-redis-node-4 portfolio-backend-redis-node-5"
      - "REDIS_CLUSTER_CREATOR=yes"
networks:
  portfolio-backend-network:
    driver: bridge
